# Generated by Django 3.1.1 on 2020-09-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_url',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='short_url',
            name='base_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='short_url',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='short_url',
            name='short_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
