# Generated by Django 3.1.1 on 2020-09-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_auto_20200922_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_url',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='short_url',
            name='base_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='short_url',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='short_url',
            name='short_url',
            field=models.CharField(max_length=100),
        ),
    ]
