# Generated by Django 3.1.1 on 2020-09-22 20:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_auto_20200923_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_url',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 20, 7, 23, 347565, tzinfo=utc)),
        ),
    ]
